# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: '**'
    tags: '*'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Create Output Directories
      run: |
        mkdir ${{ github.workspace }}\output\setup
        mkdir ${{ github.workspace }}\output\build
        xcopy /E /I ${{ github.workspace }}\setup ${{ github.workspace }}\output\setup       

    - name: Build with PS
      shell: powershell
      run: |
        mkdir ${{ github.workspace }}/build
        dir ${{ github.workspace }}
        dotnet build InfoPanel\InfoPanel.csproj -c Release --output "${{ github.workspace }}\output\build" 
        

    - name: Install and Compile Inno Setup Installer
      shell: powershell
      run: |
        cd ${{ github.workspace }}\InnoSetup
        iscc "setup.iss"          



    - name: Upload Artifact Setup
      uses: actions/upload-artifact@v1
      with:
        name: InfoPanel-Setup
        path:  "${{ github.workspace }}/InnoSetup/Output/InfoPanelSetup.exe"           

       
